services:
  app:
    container_name: gtk_app_container
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /run/dbus/system_bus_socket
    devices:
      - /dev/dri
    security_opt:
      - seccomp=unconfined